import json
import io
import os
import logging

from collections import namedtuple
from datetime import datetime, timedelta

from db import db
from io import BytesIO
from docxtpl import DocxTemplate

from model.patient import Patient
from model.address import Address
from model.users import Users
from model.user_registration import UserRegister
from model.material_requests import MaterialRequests

from utils.send_mail import send_product_request_email
from utils.constants import PDR_PROTOCOL_NUMBER
from utils.s3_api import  S3Api

class MaterialRequestObj:
    def __init__(self):
        self.loggedin_user = ""
        self.today = datetime.now().strftime("%m/%d/%Y")
        self.needed_by_date = None
        self.sequence_number = ""
        self.recipient_name = ""
        self.site_name = ""
        self.address = ""
        self.city = ""
        self.state = ""
        self.zip = ""
        self.country = ""
        self.phone = ""
        self.email = ""
        self.double_patch_qty = 0
        self.single_patch_qty = 0
        self.mdu_qty = 0
        self.starter_kit_qty = 0
        self.skin_prep_kit_qty = 0
        self.removal_kit_qty = 0
        self.placement_accessory_qty = 0
        self.ht_qty = 0
        self.ifu_qty = 0
        self.adhesive_laminate_qty = 0
        self.patcher_shipper_return_box_qty = 0
        self.su_qty = 0
        self.site_id = 0
        self.patient_id = 0
        self.special_instructions = ""

    def count_items(self):
        count = self.double_patch_qty + \
                self.single_patch_qty + \
                self.mdu_qty + \
                self.starter_kit_qty + \
                self.skin_prep_kit_qty + \
                self.removal_kit_qty + \
                self.placement_accessory_qty + \
                self.ht_qty + \
                self.ifu_qty + \
                self.adhesive_laminate_qty + \
                self.patcher_shipper_return_box_qty + \
                self.su_qty
        return count

    def to_dict(self, data):
        for key in data:
            setattr(self, key, data[key])


class MaterialRequestService:
    def __init__(self):
        pass

    def send_initial_product_request(self, logged_in_user_email: str,
                                     patient: Patient,
                                     patient_email: str) -> bool:
        logging.info("SENDING INITIAL PRODUCT REQUEST....................")
        req = MaterialRequestObj()
        user_obj = Users.find_by_email(logged_in_user_email)
        req.loggedin_user = user_obj.first_name + " " + user_obj.last_name

        material_requests_db = MaterialRequests()
        material_requests_db.num_items = 2
        material_requests_db.request_date = datetime.now()
        material_requests_db.requested_user_id = user_obj.id
        material_requests_db.patient_id = patient.id
        obj_from_db = material_requests_db.save_to_db()

        time = datetime.now() + timedelta(days=4)
        req.needed_by_date = time.strftime("%m/%d/%Y")

        # Sequence number gets generated by the database
        req.sequence_number = obj_from_db.request_number

        req.site_name = "N/A"
        # Find the patient name
        user = Users.find_by_id(patient.user_id)
        req.recipient_name = user.first_name + " " + user.last_name
        req.phone = user.phone_number
        req.email = patient_email

        # Since this is the first request, the product will be shipped to a patient.
        address = Address.find_by_id(patient.shipping_address_id)
        req.address = address.street_address_1
        req.city = address.city
        req.zip = address.postal_code
        req.country = address.country
        req.state = address.state

        req.double_patch_qty = 2
        req_json = json.dumps(req.__dict__)
        logging.debug(req_json)

        self.__send_request(req.__dict__, logged_in_user_email)
        return True

    def send_new_product_request(self, request_data: MaterialRequestObj,
                                 logged_in_user_email: str):
        # TODO Add additional logic here
        user = UserRegister.find_by_email(logged_in_user_email)

        material_requests_db = MaterialRequests()
        material_requests_db.num_items = request_data.count_items()
        material_requests_db.request_date = datetime.now()
        material_requests_db.requested_user_id = user.id
        material_requests_db.recipient = request_data.recipient_name

        if request_data.site_id > 0:
            material_requests_db.site_id = request_data.site_id

        if request_data.patient_id > 0:
            material_requests_db.patient_id = request_data.patient_id
        obj_from_db = material_requests_db.save_to_db()

        # Sequence number gets generated by the database
        request_data.sequence_number = obj_from_db.request_number

        self.__send_request(request_data.__dict__, logged_in_user_email)
        return True

    def get_filtered_material_list(self, page_number, record_per_page, request_number):
        material_list = namedtuple(
            "MaterialsList",
            (
                "request_number",
                "request_id",
                "requestor",
                "date_requested",
                "recipient",
                "items_requested"
            ),
        )

        # Get all facilities and address
        requests_query = db.session.query(MaterialRequests)
        if request_number is not None and len(request_number) > 0:
            requests_query = requests_query.filter(MaterialRequests.request_number == request_number)

        data_count = requests_query.count()
        query_data = []
        lists = []
        try:
            query_data = (
                requests_query.order_by(MaterialRequests.request_number)
                    .paginate(page_number + 1, record_per_page).items
            )
        except Exception as e:
            logging.exception(e)

        for data in query_data:
            requests = material_list(
                request_number=data.request_number,
                request_id=data.id,
                requestor="",
                date_requested=data.request_date,
                recipient=data.recipient,
                items_requested=data.num_items
            )

            lists.append(requests._asdict())

        return lists, data_count

    def __send_request(self, request_data, logged_in_user_email):
        template_file = os.path.join(os.getcwd(), "templates", "PRD_template.docx")
        logging.info(f"template file: {str(template_file)}")
        content = self.__doc_from_template(template_file, request_data)
        csv_file = self.__generate_excel(request_data)
        send_product_request_email(request_data["sequence_number"],
                                   content.read(), csv_file.read(), logged_in_user_email)

        content.seek(0)
        csv_file.seek(0)
        csv_file_buff = io.BytesIO(csv_file.getvalue().encode())
        s3api = S3Api()
        s3api.upload_material_request_form(request_data["sequence_number"],
                                           content, csv_file_buff)


    def __doc_from_template(self, template_file, data):
        template = DocxTemplate(template_file)
        template.render(data)

        docx_stream = BytesIO()
        template.save(docx_stream)
        docx_stream.seek(0)

        return docx_stream

    def __generate_excel(self, data_dict):
        import csv
        from io import StringIO
        header = ["Transaction #", "Requested By", "Date Requested", "Date Needed",
                  "Protocol #", "Recipient Shipping Information", "Recipient Phone #",
                  "Recipient Email Address", "Qty: 900-000031", "Qty: 900-000044",
                  "Qty: 900-00036", "Qty: 900-00049", "Qty: 900-00050", "Qty: 900-00051",
                  "Qty: trimmer", "Qty: IFU", "Qty: Adhesive Laminate", "Qty: Packed Starter Kit",
                  "Qty: Shipping Materials", "Qty: Return Labels", "Special Instructions"]

        data = MaterialRequestObj()
        data.to_dict(data_dict)
        address = data.address + ", " + data.city + ", " + data.state + ", " + data.zip + ", " + data.country
        csv_data = [data.sequence_number, data.loggedin_user, data.today, data.needed_by_date,
                    PDR_PROTOCOL_NUMBER, address, data.phone, data.email, " ", " ",
                    " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "]
        # TODO: Update this once the protocol template is finalized
        f = StringIO()
        csv.writer(f).writerow(header)
        csv.writer(f).writerow(csv_data)
        f.seek(0)
        return f
