image: "python:3.8"
pipelines: 
  branches: 
    feature/EC-608-implement-service-to-create-update-provider: 
      - 
        step: 
          name: "Git Checkout"
          script: 
            - "git clone git@bitbucket.org:elementsci/user-manager.git"
            - echo "Git repo cloned on the runner instance."
      - 
        step: 
          name: "Python Dependencies Installation."
          script: 
            - "pip install -r es-api/requirements.txt"
            - echo "Python requirement packages installed successfully."
