image: "python:3.8"
pipelines: 
  branches: 
    feature/EC-608-implement-service-to-create-update-provider: 
      - 
        step: 
          name: "Git Checkout"
          script: 
            - "git clone git@bitbucket.org:elementsci/user-manager.git"
            - echo "Git repo cloned on the runner instance."
      - 
        step: 
          name: "Python Dependencies Installation."
          script: 
            - "pip install -r es-api/requirements.txt"
            - echo "Python requirement packages installed successfully."
      - 
        step: 
          services: 
            - docker
          caches: 
            - pip
          name: "Building docker image and pushing it to ECR."
          script: 
            - pip install awscli
            - echo "AWS CLI installed successfully."
            - IMAGE="488323030461.dkr.ecr.us-west-1.amazonaws.com/test-es-ecr"
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - cd es-api
            - docker build -t $BITBUCKET_COMMIT .
            - echo "Docker image build successfull."
            - aws configure set aws_access_key_id "${AWS_KEY}"
            - aws configure set aws_secret_access_key "${AWS_SECRET}"
            - eval $(aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 488323030461.dkr.ecr.us-west-1.amazonaws.com)
            - docker push $IMAGE:$TAG
            - echo "Docker image pushed to ECR successfully."