"""Added Device Model

Revision ID: 33d72de6eae5
Revises: b7882d31fcd2
Create Date: 2021-01-22 08:41:09.475962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d72de6eae5'
down_revision = 'b7882d31fcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=12), nullable=True),
    sa.Column('encryption_key', sa.String(length=50), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device', schema='ES')
    # ### end Alembic commands ###
