"""Added User Model

Revision ID: 490577f4c14a
Revises: 
Create Date: 2021-01-22 07:50:50.405270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490577f4c14a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('scopee', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['ES.scope.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['ES.status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['ES.user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='ES')
    op.drop_table('user_type', schema='ES')
    op.drop_table('status', schema='ES')
    op.drop_table('scope', schema='ES')
    # ### end Alembic commands ###
