"""Modified patients schema Added provider Schema

Revision ID: 8c2d2984bca0
Revises: de8c55ebf7de
Create Date: 2021-01-29 01:39:18.994890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2d2984bca0'
down_revision = 'de8c55ebf7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ES.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.drop_constraint('patients_provider_id_fkey', 'patients', schema='ES', type_='foreignkey')
    op.drop_constraint('patients_user_id_fkey', 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'providers', ['provider_id'], ['id'], source_schema='ES', referent_schema='ES')
    op.create_foreign_key(None, 'patients', 'user', ['user_id'], ['id'], source_schema='ES', referent_schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', schema='ES', type_='foreignkey')
    op.drop_constraint(None, 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key('patients_user_id_fkey', 'patients', 'users', ['user_id'], ['id'], source_schema='ES', referent_schema='ES')
    op.create_foreign_key('patients_provider_id_fkey', 'patients', 'user', ['provider_id'], ['id'], source_schema='ES', referent_schema='ES')
    op.drop_table('providers', schema='ES')
    # ### end Alembic commands ###
