"""Added patient Module

Revision ID: b62cd0b45773
Revises: d8c2fa997d7a
Create Date: 2021-01-28 16:07:12.257454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b62cd0b45773'
down_revision = 'd8c2fa997d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=False), schema='ES')
    op.add_column('patients', sa.Column('emergenct_contact_phone', sa.String(length=12), nullable=False), schema='ES')
    op.add_column('patients', sa.Column('enrolled_at', sa.DateTime(), nullable=True), schema='ES')
    op.drop_constraint('patients_address_id_fkey', 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'user', ['provider_id'], ['id'], source_schema='ES', referent_schema='ES')
    op.drop_column('patients', 'address_id', schema='ES')
    op.drop_column('patients', 'external_patient_id', schema='ES')
    op.drop_column('patients', 'emergenct_contact_number', schema='ES')
    op.drop_column('patients', 'last_name', schema='ES')
    op.drop_column('patients', 'first_name', schema='ES')
    op.drop_column('patients', 'external_auth_id', schema='ES')
    op.drop_column('patients', 'enrolled_date', schema='ES')
    op.drop_column('patients', 'email', schema='ES')
    op.drop_column('patients', 'mobile', schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('mobile', sa.VARCHAR(length=12), autoincrement=False, nullable=False), schema='ES')
    op.add_column('patients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False), schema='ES')
    op.add_column('patients', sa.Column('enrolled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='ES')
    op.add_column('patients', sa.Column('external_auth_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='ES')
    op.add_column('patients', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False), schema='ES')
    op.add_column('patients', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False), schema='ES')
    op.add_column('patients', sa.Column('emergenct_contact_number', sa.VARCHAR(length=12), autoincrement=False, nullable=False), schema='ES')
    op.add_column('patients', sa.Column('external_patient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='ES')
    op.add_column('patients', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='ES')
    op.drop_constraint(None, 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key('patients_address_id_fkey', 'patients', 'address', ['address_id'], ['id'], source_schema='ES', referent_schema='ES')
    op.drop_column('patients', 'enrolled_at', schema='ES')
    op.drop_column('patients', 'emergenct_contact_phone', schema='ES')
    op.drop_column('patients', 'created_at', schema='ES')
    # ### end Alembic commands ###
