"""Added Patient Model

Revision ID: b7882d31fcd2
Revises: 9e4319892e2c
Create Date: 2021-01-22 08:33:41.293636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7882d31fcd2'
down_revision = '9e4319892e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=12), nullable=False),
    sa.Column('emergenct_contact_name', sa.String(length=30), nullable=False),
    sa.Column('emergenct_contact_number', sa.String(length=12), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('external_auth_id', sa.String(length=50), nullable=True),
    sa.Column('external_patient_id', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=30), nullable=True),
    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['ES.address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ES.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients', schema='ES')
    # ### end Alembic commands ###
