"""Removed column from Scope Model

Revision ID: d7c63cf5906d
Revises: 33d72de6eae5
Create Date: 2021-01-22 08:43:36.556576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c63cf5906d'
down_revision = '33d72de6eae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scope', 'scopee', schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scope', sa.Column('scopee', sa.VARCHAR(length=30), autoincrement=False, nullable=False), schema='ES')
    # ### end Alembic commands ###
