"""Added patients_devices schema

Revision ID: de8c55ebf7de
Revises: b62cd0b45773
Create Date: 2021-01-29 01:08:05.408872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de8c55ebf7de'
down_revision = 'b62cd0b45773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=12), nullable=True),
    sa.Column('encryption_key', sa.String(length=50), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.create_table('patients_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['ES.devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['ES.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.drop_table('device', schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ES".device_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('encryption_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='device_pkey'),
    schema='ES'
    )
    op.drop_table('patients_devices', schema='ES')
    op.drop_table('devices', schema='ES')
    # ### end Alembic commands ###
