"""Modify device_serial_number column type

Revision ID: 5420b4b8c4c8
Revises: b19b626d6706
Create Date: 2021-03-01 14:55:32.256252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5420b4b8c4c8'
down_revision = 'b19b626d6706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients_devices', 'device_serial_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients_devices', 'device_serial_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='ES')
    # ### end Alembic commands ###
