"""remove_rpovider_id_from_patient

Revision ID: c10c3ba64ab7
Revises: 2e6e17e28d2a
Create Date: 2021-04-28 16:56:58.360373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c10c3ba64ab7"
down_revision = "2e6e17e28d2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "provider_id", schema="ES")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column("provider_id", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="ES",
    )
    # ### end Alembic commands ###
