"""newMigration

Revision ID: 89c3a0299380
Revises: 6d418a4c9ca8
Create Date: 2021-12-16 18:26:10.839169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c3a0299380'
down_revision = '6d418a4c9ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requests', sa.Column('requested_user_id', sa.Integer(), nullable=True), schema='ES')
    op.add_column('material_requests', sa.Column('recipient_user_id', sa.Integer(), nullable=True), schema='ES')
    op.drop_constraint('material_requests_requested_user_fkey', 'material_requests', schema='ES', type_='foreignkey')
    op.drop_constraint('material_requests_patient_id_fkey', 'material_requests', schema='ES', type_='foreignkey')
    op.create_foreign_key(None, 'material_requests', 'users', ['requested_user_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.create_foreign_key(None, 'material_requests', 'users', ['recipient_user_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.drop_column('material_requests', 'requested_user', schema='ES')
    op.drop_column('material_requests', 'patient_id', schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requests', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='ES')
    op.add_column('material_requests', sa.Column('requested_user', sa.INTEGER(), autoincrement=False, nullable=False), schema='ES')
    op.drop_constraint(None, 'material_requests', schema='ES', type_='foreignkey')
    op.drop_constraint(None, 'material_requests', schema='ES', type_='foreignkey')
    op.create_foreign_key('material_requests_patient_id_fkey', 'material_requests', 'patients', ['patient_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.create_foreign_key('material_requests_requested_user_fkey', 'material_requests', 'users', ['requested_user'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.drop_column('material_requests', 'recipient_user_id', schema='ES')
    op.drop_column('material_requests', 'requested_user_id', schema='ES')
    # ### end Alembic commands ###
