"""add_user_otps

Revision ID: 565199d77ed7
Revises: 3254391e7b2f
Create Date: 2021-03-16 15:12:20.824315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565199d77ed7'
down_revision = '3254391e7b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=255), nullable=False),
    sa.Column('temp_password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_otps', schema='ES')
    # ### end Alembic commands ###
