"""add_role_types

Revision ID: 3254391e7b2f
Revises: cd9b99224e1d
Create Date: 2021-03-16 15:11:17.174723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3254391e7b2f'
down_revision = 'cd9b99224e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('role_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_types', schema='ES')
    # ### end Alembic commands ###
