"""add_salvos_table

Revision ID: 89af2773f902
Revises: 958eb52159b6
Create Date: 2021-03-16 15:24:09.502644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89af2773f902'
down_revision = '958eb52159b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salvos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('therapy_report_id', sa.Integer(), nullable=False),
    sa.Column('device_serial_number', sa.Integer(), nullable=True),
    sa.Column('clinician_verified_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data_location', sa.String(length=100), nullable=True),
    sa.Column('pdf_location', sa.String(length=100), nullable=True),
    sa.Column('receiver_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('receiver_sent_at', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['therapy_report_id'], ['ES.therapy_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salvos', schema='ES')
    # ### end Alembic commands ###
