"""add_deactivated_col

Revision ID: f41d5ee07974
Revises: a249b99bb344
Create Date: 2021-08-25 12:29:18.692058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41d5ee07974'
down_revision = 'a249b99bb344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('deactivated', sa.Boolean(), nullable=True), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'deactivated', schema='ES')
    # ### end Alembic commands ###
