"""add_facilities_table

Revision ID: 39031f91b16d
Revises: a32d990b6755
Create Date: 2021-03-16 15:19:34.645362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39031f91b16d'
down_revision = 'a32d990b6755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('on_call_phone', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['ES.addresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facilities', schema='ES')
    # ### end Alembic commands ###
