"""add_device_statuses_and_metrics_tables

Revision ID: b32d00965447
Revises: 0f542c0c89e3
Create Date: 2021-04-12 14:39:03.199268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b32d00965447'
down_revision = '0f542c0c89e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_serial_number', sa.String(length=50), nullable=False),
    sa.Column('device_metrics_id', sa.Integer(), nullable=True),
    sa.Column('device_metrics_data', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_metrics_id'], ['ES.device_metrics_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.create_table('device_ui_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_serial_number', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['ES.device_ui_status_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='ES')
    op.alter_column('salvos', 'device_serial_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='ES')
    op.drop_column('salvos', 'shock_count', schema='ES')
    op.alter_column('facilities', 'on_call_phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True,
               schema='ES')
    op.create_table('patches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ES".patches_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('patient_device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_device_id'], ['ES.patients_devices.id'], name='patches_patient_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='patches_pkey'),
    schema='ES'
    )
    op.drop_table('device_ui_statuses', schema='ES')
    op.drop_table('device_metrics', schema='ES')
    op.drop_table('authentication_tokens', schema='ES')
    # ### end Alembic commands ###
