"""add_patches_table

Revision ID: e50d1e1633c7
Revises: 60f77fec092a
Create Date: 2021-03-16 15:38:42.175219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50d1e1633c7'
down_revision = '60f77fec092a'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_device_id'], ['ES.patients_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patches', schema='ES')
    # ### end Alembic commands ###
