"""add_indication_column_to_patients

Revision ID: 6e73fbf5285c
Revises: e50d1e1633c7
Create Date: 2021-03-29 21:05:19.021718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e73fbf5285c'
down_revision = 'e50d1e1633c7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('indication', sa.String(length=40), nullable=True), schema='ES')
    patients = sa.sql.table("patients", sa.Column("indication", sa.String(length=40)), schema="ES")

    op.execute(
        patients.update()
        .values(indication="VT/VF")
    )

    op.alter_column('patients', 'indication',
               existing_type=sa.String(length=40),
               nullable=False,
               schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'indication', schema='ES')
    # ### end Alembic commands ###
