"""changes to material requests model

Revision ID: 33420c6c5448
Revises: 7264621acdd6
Create Date: 2021-11-19 12:36:57.408994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33420c6c5448'
down_revision = '7264621acdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_requests', sa.Column('recipient', sa.String(length=100), nullable=True), schema='ES')
    op.add_column('material_requests', sa.Column('site_id', sa.Integer(), nullable=True), schema='ES')
    op.add_column('material_requests', sa.Column('patient_id', sa.Integer(), nullable=True), schema='ES')
    op.create_foreign_key(None, 'material_requests', 'patients', ['patient_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.create_foreign_key(None, 'material_requests', 'facilities', ['site_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_requests', schema='ES', type_='foreignkey')
    op.drop_constraint(None, 'material_requests', schema='ES', type_='foreignkey')
    op.drop_column('material_requests', 'patient_id', schema='ES')
    op.drop_column('material_requests', 'site_id', schema='ES')
    op.drop_column('material_requests', 'recipient', schema='ES')
    # ### end Alembic commands ###
