"""Indicate if site is active or not

Revision ID: 7264621acdd6
Revises: 3a83bbdac417
Create Date: 2021-11-15 15:42:17.427158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7264621acdd6'
down_revision = '3a83bbdac417'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy.sql import expression
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('is_active', sa.Boolean(),
                                          server_default=expression.true(), default=True, nullable=False), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'is_active', schema='ES')
    # ### end Alembic commands ###
