"""add_patients_table

Revision ID: 903c7bdef169
Revises: fbbe88ec83d6
Create Date: 2021-03-16 15:21:24.107093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903c7bdef169'
down_revision = 'fbbe88ec83d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=30), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=12), nullable=False),
    sa.Column('date_of_birth', sa.String(length=30), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ES.providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ES.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients', schema='ES')
    # ### end Alembic commands ###
