"""Added external id to the user table

Revision ID: 320adfed0282
Revises: 51e5ab6eda8e
Create Date: 2021-08-17 08:49:07.347789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320adfed0282'
down_revision = '51e5ab6eda8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_user_id', sa.String(length=10), nullable=True), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'external_user_id', schema='ES')
    # ### end Alembic commands ###
