"""add_locked_column_to_registrations_table

Revision ID: a22708e8a89e
Revises: 2f2f2cc4480d
Create Date: 2021-06-16 15:16:39.275511

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a22708e8a89e"
down_revision = "2f2f2cc4480d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registrations", sa.Column("locked", sa.Boolean(), nullable=True), schema="ES"
    )

    registrations = sa.sql.table(
        "registrations", sa.Column("locked", sa.Boolean()), schema="ES"
    )

    op.execute(registrations.update().values(locked=False))

    op.alter_column(
        "registrations",
        "locked",
        existing_type=sa.Boolean(),
        nullable=False,
        schema="ES",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registrations", "locked", schema="ES")
    # ### end Alembic commands ###
