"""add_ext_id_facilities

Revision ID: af5fd658e88f
Revises: 51e5ab6eda8e
Create Date: 2021-08-16 11:52:37.192990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5fd658e88f'
down_revision = '51e5ab6eda8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('external_facility_id', sa.String(length=6), nullable=False), schema='ES')
    op.alter_column('registrations', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registrations', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='ES')
    op.drop_column('facilities', 'external_facility_id', schema='ES')
    # ### end Alembic commands ###
