"""add_patients_providers_table

Revision ID: 60f77fec092a
Revises: 7d03fc575517
Create Date: 2021-03-16 15:37:03.387746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f77fec092a'
down_revision = '7d03fc575517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('provider_role_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['ES.patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ES.providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_role_id'], ['ES.provider_role_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients_providers', schema='ES')
    # ### end Alembic commands ###
