"""add address id to the patient table

Revision ID: 0bbf0678aa8c
Revises: 2e6e17e28d2a
Create Date: 2021-05-01 09:41:16.697272

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0bbf0678aa8c"
down_revision = "c10c3ba64ab7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients", sa.Column("address_id", sa.Integer(), nullable=True), schema="ES"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "address_id", schema="ES")
    # ### end Alembic commands ###
