"""update_db_to_match_models

Revision ID: 2f2f2cc4480d
Revises: 0bbf0678aa8c
Create Date: 2021-06-16 14:37:26.001835

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f2f2cc4480d"
down_revision = "0bbf0678aa8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facilities",
        "on_call_phone",
        existing_type=sa.VARCHAR(length=12),
        nullable=False,
        schema="ES",
    )
    op.create_foreign_key(
        None,
        "patients",
        "addresses",
        ["address_id"],
        ["id"],
        source_schema="ES",
        referent_schema="ES",
        ondelete="CASCADE",
    )
    op.alter_column(
        "salvos",
        "device_serial_number",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
        schema="ES",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salvos",
        "device_serial_number",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="ES",
    )
    op.drop_constraint(None, "patients", schema="ES", type_="foreignkey")
    op.alter_column(
        "facilities",
        "on_call_phone",
        existing_type=sa.VARCHAR(length=12),
        nullable=True,
        schema="ES",
    )
    # ### end Alembic commands ###
