"""add_newsletters_table

Revision ID: 51e5ab6eda8e
Revises: a22708e8a89e
Create Date: 2021-07-12 11:52:23.826246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e5ab6eda8e'
down_revision = 'a22708e8a89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ES.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletters', schema='ES')
    # ### end Alembic commands ###
