"""Patients patches table

Revision ID: c5f5f5271686
Revises: 9d2b241d85bf
Create Date: 2021-08-24 08:52:07.415363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5f5f5271686'
down_revision = '9d2b241d85bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients_patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('patch_lot_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patch_returned_date', sa.DateTime(), nullable=True),
    sa.Column('patch_shipped_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['ES.patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.drop_table('patches', schema='ES')
    op.add_column('patients', sa.Column('permanent_address_id', sa.Integer(), nullable=True), schema='ES')
    op.add_column('patients', sa.Column('shipping_address_id', sa.Integer(), nullable=True), schema='ES')
    op.drop_constraint('patients_address_id_fkey', 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'addresses', ['permanent_address_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.create_foreign_key(None, 'patients', 'addresses', ['shipping_address_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.drop_column('patients', 'address_id', schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='ES')
    op.drop_constraint(None, 'patients', schema='ES', type_='foreignkey')
    op.drop_constraint(None, 'patients', schema='ES', type_='foreignkey')
    op.create_foreign_key('patients_address_id_fkey', 'patients', 'addresses', ['address_id'], ['id'], source_schema='ES', referent_schema='ES', ondelete='CASCADE')
    op.drop_column('patients', 'shipping_address_id', schema='ES')
    op.drop_column('patients', 'permanent_address_id', schema='ES')
    op.create_table('patches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ES".patches_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('patient_device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patch_serial_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_device_id'], ['ES.patients_devices.id'], name='patches_patient_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='patches_pkey'),
    schema='ES'
    )
    op.drop_table('patients_patches', schema='ES')
    # ### end Alembic commands ###
