"""add-unenrolled_at-column

Revision ID: a249b99bb344
Revises: c5f5f5271686
Create Date: 2021-08-24 16:18:23.804803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a249b99bb344'
down_revision = 'c5f5f5271686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('unenrolled_at', sa.DateTime(), nullable=True), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'unenrolled_at', schema='ES')
    # ### end Alembic commands ###
