"""update_address_facilities

Revision ID: 2f151c96b0a9
Revises: af5fd658e88f
Create Date: 2021-08-16 12:03:41.048030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f151c96b0a9'
down_revision = 'af5fd658e88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ES')
    # ### end Alembic commands ###
