"""is_active

Revision ID: 4ff78f46eaa1
Revises: f41d5ee07974
Create Date: 2021-08-31 12:53:00.502692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff78f46eaa1'
down_revision = 'f41d5ee07974'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy.sql import expression
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_devices', sa.Column('is_active', sa.Boolean(),
                                                server_default=expression.true(), default=True, nullable=False),
                  schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_devices', 'is_active', schema='ES')
    # ### end Alembic commands ###
