"""add_serial_number_to_patches_table

Revision ID: 2e6e17e28d2a
Revises: 89943f1d2444
Create Date: 2021-04-20 10:24:03.797701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6e17e28d2a'
down_revision = '89943f1d2444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('patch_serial_number', sa.String(length=30), nullable=False), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'patch_serial_number', schema='ES')
    # ### end Alembic commands ###
