"""add_therapy_reports_table

Revision ID: 958eb52159b6
Revises: e136da258567
Create Date: 2021-03-16 15:23:22.045899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958eb52159b6'
down_revision = 'e136da258567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('device_serial_number', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['ES.patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapy_reports', schema='ES')
    # ### end Alembic commands ###
