"""user changes

Revision ID: 3c0f264a9678
Revises: 33420c6c5448
Create Date: 2021-12-02 15:15:31.847865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0f264a9678'
down_revision = '33420c6c5448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['ES.addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['ES.facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ES.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    op.add_column('user_statuses', sa.Column('notes', sa.String(length=200), nullable=True), schema='ES')
    op.add_column('user_statuses', sa.Column('deactivation_reason', sa.String(length=500), nullable=True), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_statuses', 'deactivation_reason', schema='ES')
    op.drop_column('user_statuses', 'notes', schema='ES')
    op.drop_table('study_managers', schema='ES')
    # ### end Alembic commands ###
