"""empty message

Revision ID: 6a07b2461b02
Revises: d358f61fd4b3
Create Date: 2022-06-09 09:53:25.773916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a07b2461b02'
down_revision = 'd358f61fd4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('all_day_phone', sa.String(length=12), nullable=True), schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'all_day_phone', schema='ES')
    # ### end Alembic commands ###
