"""add new provider table

Revision ID: 517faa81285d
Revises: e392a81364a3
Create Date: 2022-05-03 12:53:19.468857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517faa81285d'
down_revision = 'e392a81364a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ES.facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ES.providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ES'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_facility', schema='ES')
    # ### end Alembic commands ###
