"""Modify device_serial_number column type

Revision ID: 69a6c08d8dc0
Revises: ad2ecdd38dab
Create Date: 2021-03-01 20:29:12.997899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69a6c08d8dc0'
down_revision = 'ad2ecdd38dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients_devices', 'device_serial_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False,
               schema='ES')
    op.alter_column('therapy_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='ES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapy_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='ES')
    op.alter_column('patients_devices', 'device_serial_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='ES')
    # ### end Alembic commands ###
